### ISSUE TITLE
第二版Debug部分，无法运行

### ISSUE THREAD

**Issue by HuitMahoon** [PyJun/Recover_Figures#1]
python -m Debug , 生成碎片后无法还原。因为 ./Debug/Package 目录下遗漏了opencv_world410.dll 文件。把文件复制到此目录即可。

**Comment by PyJun** [comment]
你用release就行了，
不建议用debug。



---原始邮件---
发件人: "hui Teng"<notifications@github.com&gt;
发送时间: 2020年10月30日(周五) 下午3:31
收件人: "PyJun/Recover_Figures"<Recover_Figures@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Recover_Figures] 第二版Debug部分，无法运行 (#1)




 
python -m Debug , 生成碎片后无法还原。因为 ./Debug/Package 目录下遗漏了opencv_world410.dll 文件。把文件复制到此目录即可。
